
CONNECT SYS_MECANICA/MECANICA

CREATE TABLE CLIENTE
(
	ID_RUC_CLIENTE       CHAR(15) NOT NULL ,
	NOMBRE               VARCHAR2(50) NULL ,
	APELLIDO_PATERNO     VARCHAR2(50) NULL ,
	APELLIDO_MATERNO     VARCHAR2(50) NULL ,
	CUIDAD               VARCHAR2(50) NULL ,
	CORREO               VARCHAR2(50) NULL ,
	TELEFONO_FIJO        VARCHAR2(50) NULL ,
	TELEFONO_MOVIL       VARCHAR2(50) NULL 
);



ALTER TABLE CLIENTE
	ADD  PRIMARY KEY (ID_RUC_CLIENTE);



CREATE TABLE INVENTARIO
(
	ID_PRODUCTO          CHAR(10) NOT NULL ,
	TIPO_PRODUCTO        VARCHAR2(50) NULL ,
	MARCA                VARCHAR2(50) NULL ,
	MODELO               VARCHAR2(50) NULL ,
	VALOR                VARCHAR2(50) NULL ,
	CANTIDAD             NUMBER(5) NULL ,
	ESTADO               VARCHAR2(10) NULL 
);



ALTER TABLE INVENTARIO
	ADD  PRIMARY KEY (ID_PRODUCTO);



CREATE TABLE MANO__DE_OBRA
(
	ID_MANO_DE_OBRA      CHAR(10) NOT NULL ,
	DETALLE              VARCHAR2(50) NULL ,
	TIEMPO               DATE NULL ,
	VALOR                NUMBER(5) NULL ,
	ID_RUC_MECANICO      CHAR(15) NULL ,
	ID_ORDEN_TRABAJO     CHAR(10) NULL 
);



ALTER TABLE MANO__DE_OBRA
	ADD  PRIMARY KEY (ID_MANO_DE_OBRA);



CREATE TABLE MECANICO
(
	ID_RUC_MECANICO      CHAR(15) NOT NULL ,
	NOMBRE               VARCHAR2(50) NULL ,
	APELLIDO_PATERNO     VARCHAR2(50) NULL ,
	APELLIDO_MATERNO     VARCHAR2(50) NULL ,
	TELEFONO             VARCHAR2(50) NULL ,
	DIRECCION            VARCHAR2(50) NULL ,
	CORREO               VARCHAR2(50) NULL ,
	ESPECIALIDAD         VARCHAR2(50) NULL ,
	ESTADO               CHAR(10) NULL 
);



ALTER TABLE MECANICO
	ADD  PRIMARY KEY (ID_RUC_MECANICO);



CREATE TABLE ORDEN_DE_TRABAJO
(
	ID_ORDEN_TRABAJO     CHAR(10) NOT NULL ,
	FECHA                DATE NULL ,
	NIVELCOMBISTIBLE     VARCHAR2(50) NULL ,
	CANTIDADTAPARUEDA    NUMBER(5) NULL ,
	RUEDAREPUESTO        NUMBER(5) NULL ,
	KILOMETRAJE          NUMBER(5) NULL ,
	FORMA_PAGO           VARCHAR2(50) NULL ,
	PLAZA                VARCHAR2(50) NULL ,
	TIPOTARJETACREDITO   VARCHAR2(50) NULL ,
	NUMEROCUOTAS         NUMBER(5) NULL ,
	FECHAPAGO            DATE NULL ,
	ID_placa_vehiculo    CHAR(10) NULL ,
	ID_USUARIO           CHAR(10) NULL 
);



ALTER TABLE ORDEN_DE_TRABAJO
	ADD  PRIMARY KEY (ID_ORDEN_TRABAJO);



CREATE TABLE REPUESTO_ORDEN_TRABAJO
(
	ID_REPUESTO_ORDEN    CHAR(10) NOT NULL ,
	VALOR_UNITARIO       NUMBER(5) NULL ,
	CANTIDAD             NUMBER(5) NULL ,
	ID_ORDEN_TRABAJO     CHAR(10) NULL ,
	ID_PRODUCTO          CHAR(10) NULL 
);



ALTER TABLE REPUESTO_ORDEN_TRABAJO
	ADD  PRIMARY KEY (ID_REPUESTO_ORDEN);



CREATE TABLE USUARIO
(
	ID_USUARIO           CHAR(10) NOT NULL ,
	NOMBRE               VARCHAR2(50) NULL ,
	APELLIDO_PATERNO     VARCHAR2(50) NULL ,
	APELLIDO_MATERNO     VARCHAR2(50) NULL ,
	TELEFONO             VARCHAR2(50) NULL ,
	PASSWORD             VARCHAR2(50) NULL ,
	CORREO               VARCHAR2(50) NULL ,
	DIRRECCION           VARCHAR2(50) NULL ,
	TIPO_DE_USUARIO      CHAR(10) NULL 
);



ALTER TABLE USUARIO
	ADD  PRIMARY KEY (ID_USUARIO);



CREATE TABLE VEHICULO
(
	ID_placa_vehiculo    CHAR(10) NOT NULL ,
	Marca                VARCHAR2(50) NULL ,
	Modelo               VARCHAR2(50) NULL ,
	Año                  NUMBER(5) NULL ,
	Color                VARCHAR2(50) NULL ,
	Kilometraje          VARCHAR2(50) NULL 
);



ALTER TABLE VEHICULO
	ADD  PRIMARY KEY (ID_placa_vehiculo);



CREATE TABLE VEHICULO_CLIENTE
(
	ID_placa_vehiculo    CHAR(10) NOT NULL ,
	ID_RUC_CLIENTE       CHAR(15) NOT NULL 
);





ALTER TABLE MANO__DE_OBRA
	ADD (FOREIGN KEY (ID_RUC_MECANICO) REFERENCES MECANICO 
(ID_RUC_MECANICO) ON DELETE SET NULL);



ALTER TABLE MANO__DE_OBRA
	ADD (FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES 
ORDEN_DE_TRABAJO (ID_ORDEN_TRABAJO) ON DELETE SET NULL);



ALTER TABLE ORDEN_DE_TRABAJO
	ADD (FOREIGN KEY (ID_placa_vehiculo) REFERENCES VEHICULO 
(ID_placa_vehiculo) ON DELETE SET NULL);



ALTER TABLE ORDEN_DE_TRABAJO
	ADD (FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO 
(ID_USUARIO) ON DELETE SET NULL);



ALTER TABLE REPUESTO_ORDEN_TRABAJO
	ADD (FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES 
ORDEN_DE_TRABAJO (ID_ORDEN_TRABAJO) ON DELETE SET NULL);



ALTER TABLE REPUESTO_ORDEN_TRABAJO
	ADD (FOREIGN KEY (ID_PRODUCTO) REFERENCES INVENTARIO 
(ID_PRODUCTO) ON DELETE SET NULL);



ALTER TABLE VEHICULO_CLIENTE
	ADD (FOREIGN KEY (ID_placa_vehiculo) REFERENCES VEHICULO 
(ID_placa_vehiculo));



ALTER TABLE VEHICULO_CLIENTE
	ADD (FOREIGN KEY (ID_RUC_CLIENTE) REFERENCES CLIENTE 
(ID_RUC_CLIENTE));

show user;