-- Asignando permisos al rol AUDITORIA_DB
GRANT CONNECT, RESOURCE, DBA TO AUDITORIA_DB;

-- Asignando permisos al rol CONSULTA_DB
GRANT CONNECT, RESOURCE TO CONSULTA_DB;

-- ASIGNADO LECTURA A TODAS LAS TABLAS DEL ESQUE SYS_MECANICA
BEGIN
    FOR R IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'SYS_MECANICA') 
    LOOP   
        EXECUTE IMMEDIATE 'GRANT SELECT ON SYS_MECANICA.' || R.TABLE_NAME || ' TO CONSULTA_DB';    
    END LOOP;
END;
/


-- CREAR USUARIO --
-- Verifica si un existe el usuario ES_AUDITORIA
DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER ES_AUDITORIA CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'ES_AUDITORIA';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/

--Crea el usuario auditoria 
CREATE USER ES_AUDITORIA IDENTIFIED BY  auditoria

-- ASIGNAR EL ROL AUDITORIA_DB AL USUARIO AUDITORIA
GRANT AUDITORIA_DB TO ES_AUDITORIA


-- Verifica si un existe el usuario ES_CONSULTA
DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER ES_CONSULTA CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'ES_CONSULTA';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/

--Crea el usuario mecanica 
CREATE USER ES_CONSULTA IDENTIFIED BY  consulta

GRANT CONSULTA_DB TO ES_CONSULTA