
SELECT * FROM dba_segments WHERE OWNER='SCOTT';

SELECT * FROM dba_tablespaces;

CREATE TABLESPACE TS_DEMO01
DATAFILE 'C:\app\Alumno\oradata\orcl\TS_DEMO01.DBF'
SIZE 5M;

DROP TABLE TBL_DEMO01 PURGE;


CREATE TABLE TBL_DEMO01(
    ID NUMBER CONSTRAINT PK_TBL_DEMO01 PRIMARY KEY,
    DATO VARCHAR2(100)
) TABLESPACE TS_DEMO01;


SELECT * FROM dba_extents 
WHERE TABLESPACE_NAME = 'TS_DEMO01';


CREATE SEQUENCE SQ_DEMO;

BEGIN
    FOR I IN 1 .. 10000 LOOP
        INSERT INTO TBL_DEMO01
        VALUES(SQ_DEMO.NEXTVAL, 'VAMOS BOYS');
    END LOOP;
END;

COMMIT;

SELECT * FROM dba_extents 
WHERE TABLESPACE_NAME = 'TS_DEMO01';

----------------------------------------------------------

CREATE TABLESPACE TS_DEMO02
DATAFILE 'C:\app\Alumno\oradata\orcl\TS_DEMO02.DBF'
SIZE 5M 
EXTENT MANAGEMENT LOCAL UNIFORM;

CREATE TABLE TBL_DEMO02(
    ID NUMBER CONSTRAINT PK_TBL_DEMO02 PRIMARY KEY,
    DATO VARCHAR2(100)
) TABLESPACE TS_DEMO02;

SELECT * FROM dba_extents 
WHERE TABLESPACE_NAME = 'TS_DEMO02';

BEGIN
    FOR I IN 1 .. 100000 LOOP
        INSERT INTO TBL_DEMO02
        VALUES(SQ_DEMO.NEXTVAL, 'ECHA MUNI');
    END LOOP;
END;

COMMIT;

SELECT 1048576 / 1024 / 1024 FROM DUAL;
