BEGIN
    FOR R IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'SIMEM') 
    LOOP   
        EXECUTE IMMEDIATE 'GRANT SELECT ON SIMEM.' || R.TABLE_NAME || ' TO SISCE WITH GRANT OPTION';    
    END LOOP;
END;
/