
CREATE TABLESPACE TBS_ORDEN
DATAFILE 'C:\app\Alumno\oradata\orcl\DF_ORDEN.DBF'
SIZE 10M;

CREATE USER ORDEN
IDENTIFIED BY orden2000
DEFAULT TABLESPACE TBS_ORDEN
QUOTA UNLIMITED ON TBS_ORDEN;

SELECT 
USERNAME, default_tablespace, temporary_tablespace
FROM DBA_USERS
WHERE USERNAME LIKE 'ORDEN%';


GRANT CREATE SESSION TO ORDEN;
GRANT CREATE TABLE TO ORDEN;


GRANT REFERENCES ON CLIPRO.CLIENTES TO ORDEN;
GRANT REFERENCES ON ADMI.EMPLEADOS TO ORDEN;

CREATE TABLE ORDEN.ORDEN(
  ORD_Codigo NUMBER(15, 0) NOT NULL,
  CLI_Codigo1 CHAR(5 CHAR) NOT NULL,
  EMP_Codigo1 NUMBER(10, 0) NOT NULL,
  ORD_OrderDate VARCHAR2(20 CHAR)NOT NULL, 
  ORD_RequeridDate VARCHAR2(20 CHAR)NOT NULL,  
  ORD_ShippedDate VARCHAR2(20 CHAR)NOT NULL, 
  ORD_Compañia VARCHAR2(100)NOT NULL,
  ORD_ShipName VARCHAR2(100)NOT NULL,
  ORD_ShipAddress VARCHAR2(100)NOT NULL,
  ORD_ShipCity VARCHAR2(100)NOT NULL,
  ORD_ShipRegion VARCHAR2(100)NOT NULL,
  ORD_ShipPostalCode NUMBER(10, 0)NOT NULL,
  ORD_ShipCountry VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_Orden PRIMARY KEY(ORD_Codigo),
  CONSTRAINT FK_ORDEN_CLIENTES FOREIGN KEY(CLI_Codigo1) REFERENCES CLIPRO.CLIENTES(CLI_Codigo),
  CONSTRAINT FK_ORDEN_EMPLEADOS FOREIGN KEY(EMP_Codigo1) REFERENCES ADMI.EMPLEADOS(EMP_Codigo)
);

CREATE SEQUENCE SEQ_ORDEN;

Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'ALFKI',1,'10/01/19','17/01/19','15/01/19','Ransa','Envio 2','Av. Argentina 144Cercado de Lima 15079','Lima','Lima',1950,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'ANATR',1,'11/02/19','14/02/19','13/02/19','Orion','Envio 3','Calle 17, n° 455, Urbanización Corpac San Isidro','Lima','Lima',1954,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'BLAUS',1,'12/03/19','19/03/19','17/03/19','Calin SAC','Envio 4','Av. Arequipa 2625 Lince','Lima','Lima',1930,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'AROUT',1,'13/05/19','21/05/19','17/05/19','Fleurs','Envio 6','Avenida Jorge Basadre 498 San Isidro','Lima','Lima',1621,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'BERGS',1,'14/06/19','18/06/19','15/06/19','Gumisa','Envio 9','Calle Los Pinos, 490 San Isidro ','Lima','Lima',1741,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'BLAUS',1,'15/07/19','23/07/19','19/07/19','Ferreyros','Envio 11','Av. Venezuela 681Breña ','Lima','Lima',1560,'Peru');
Insert into  ORDEN.ORDEN values (SEQ_ORDEN.NEXTVAL,'BLONP',1,'16/09/19','25/09/19','22/09/19','Sithemsa','Envio 12','Av. Petit ThouarsMiraflores N° 5201','Lima','Lima',1310,'Peru');
commit;
SELECT *FROM ORDEN.ORDEN;


GRANT REFERENCES ON PRODUCTOS.PRODUCTOS TO ORDEN;

CREATE TABLE ORDEN.ORDERDETAILS(
  ORD_Codigo1 NUMBER(10, 0) NOT NULL,
  PRD_Codigo1 NUMBER(10, 0) NOT NULL,
  ORDET_UnitPrice NUMBER(38, 2) NOT NULL,
  ORDET_Quantity VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY(ORD_Codigo1) REFERENCES ORDEN.ORDEN(ORD_Codigo),
  CONSTRAINT FK_ORDERDETAILS_PRODUCTOS FOREIGN KEY(PRD_Codigo1) REFERENCES PRODUCTOS.PRODUCTOS(PRD_Codigo)
);

Insert into ORDEN.ORDERDETAILS values (2,1,14.0000,'12');
Insert into ORDEN.ORDERDETAILS values (2,2,9.8000,'10');
Insert into ORDEN.ORDERDETAILS values (2,3,34.8000,'5');
Insert into ORDEN.ORDERDETAILS values (3,4,18.6000,'9');
Insert into ORDEN.ORDERDETAILS values (3,5,42.4000,'40');
Insert into ORDEN.ORDERDETAILS values (4,6,7.7000,'10');
Insert into ORDEN.ORDERDETAILS values (4,7,42.4000,'35');
Insert into ORDEN.ORDERDETAILS values (4,8,16.8000,'15');
COMMIT;
SELECT *FROM ORDEN.ORDERDETAILS