

GRANT CONNECT TO ADMI;
GRANT CONNECT TO ORDEN;
GRANT CONNECT TO PRODUCTOS;
GRANT CONNECT TO CLIPRO;

GRANT RESOURCE TO ADMI;
GRANT RESOURCE TO ORDEN;
GRANT RESOURCE TO PRODUCTOS;
GRANT RESOURCE TO CLIPRO;

CREATE ROLE CONSULTA;
GRANT ALL ON PRODUCTOS.PRODUCTOS TO CONSULTA;
GRANT ALL ON CLIPRO.PROVEEDORES TO CONSULTA;
GRANT ALL ON CLIPRO.CLIENTES TO CONSULTA;
GRANT ALL ON ORDEN.ORDEN TO CONSULTA;
GRANT ALL ON ORDEN.ORDERDETAILS TO CONSULTA;

GRANT CONSULTA TO ADMI;